---
- name: VM_Info playbook
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "xx.xx.xx.xx"
      nutanix_username: "username"
      nutanix_password: "password"
      validate_certs: false

  tasks:
  - name: Setting Variables
    set_fact:
      vm_name: "nameofvm"

  - name: List vms using name filter criteria
    ntnx_vms_info:
      filter:
        vm_name: "{{ vm_name }}"
      kind: vm
    register: result
    ignore_errors: True

  # - name: List vms using length, offset and ascending vm_name sorting
  #   ntnx_vms_info:
  #     length: 10
  #     offset: 1
  #     sort_order: "ASCENDING"
  #     sort_attribute: "vm_name"
  #   register: result
  #   ignore_errors: True

  - name: Print host list
    ansible.builtin.debug:
      var: result
    when: result is defined